import { useEffect, useState } from 'react'
import { Alert, Badge, Button, Card, Col, Empty, Form, message, Row, Select, Space, Spin, Statistic, Table, Tabs, Tag } from 'antd'
import { CheckSquareOutlined, CustomerServiceOutlined, DownloadOutlined, FileTextOutlined, MailOutlined, MessageOutlined, PrinterOutlined, ReloadOutlined, TeamOutlined } from '@ant-design/icons'
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { apiFetch } from '../utils/api'
import PersianDatePicker from '../components/PersianDatePicker'

const API='http://localhost:5043/api/v1'
const COLORS=['#8b1a6b','#1677ff','#52c41a','#fa8c16','#f5222d','#722ed1']
const faDate=(v?:string)=>v?new Date(v).toLocaleDateString('fa-IR'):'—'
const typeLabel:Record<string,string>={Internal:'داخلی',Incoming:'وارده',Outgoing:'صادره'}
const statusLabel:Record<string,string>={Draft:'پیش‌نویس',Sent:'ارسال شده',Received:'دریافت شده',InReview:'در بررسی',Signed:'امضا شده',Referred:'ارجاع شده',Archived:'بایگانی',Cancelled:'لغو شده',Todo:'جدید',InProgress:'در حال انجام',InReviewTask:'بازبینی',Done:'تکمیل شده',CancelledTask:'لغو شده',open:'باز',inprogress:'در حال بررسی',waiting:'در انتظار',resolved:'حل شده',closed:'بسته',manager_pending:'در بررسی مدیر',hr_pending:'در بررسی منابع انسانی',approved:'تأیید نهایی',completed:'خاتمه یافته',rejected:'رد شده',returned:'برگشت برای اصلاح'}
const labelStatus=(value:string)=>statusLabel[value]||value
let reportsCache:{data:any;at:number}|undefined

export default function ReportsPage(){
  const [data,setData]=useState<any>()
  const [loading,setLoading]=useState(true)
  const [leaveUsers,setLeaveUsers]=useState<any[]>([])
  const [leaveRows,setLeaveRows]=useState<any[]>([])
  const [pendingRows,setPendingRows]=useState<any[]>([])
  const [leaveLoading,setLeaveLoading]=useState(false)
  const [leaveForm]=Form.useForm()
  const load=async(force=false)=>{if(!force&&reportsCache&&Date.now()-reportsCache.at<60000){setData(reportsCache.data);setLoading(false);return}setLoading(true);const response=await apiFetch(`${API}/reports/dashboard`);const result=await response.json().catch(()=>({}));setLoading(false);if(!response.ok){message.error(result.message||'دریافت گزارش‌ها انجام نشد');return}reportsCache={data:result,at:Date.now()};setData(result)}
  const loadLeave=async(values?:any)=>{setLeaveLoading(true);const params=new URLSearchParams();if(values?.userId)params.set('userId',values.userId);if(values?.fromDate)params.set('fromDate',values.fromDate);if(values?.toDate)params.set('toDate',values.toDate);const response=await apiFetch(`${API}/reports/forms/leave?${params}`);const result=await response.json().catch(()=>({}));setLeaveLoading(false);if(!response.ok){message.error(result.message||'دریافت گزارش مرخصی انجام نشد');return}setLeaveRows(result)}
  const loadPending=async()=>{const response=await apiFetch(`${API}/reports/forms/pending`);if(response.ok)setPendingRows(await response.json())}
  const loadFormReports=async()=>{const usersResponse=await apiFetch(`${API}/reports/forms/users`);const usersResult=await usersResponse.json().catch(()=>({}));if(usersResponse.ok&&Array.isArray(usersResult))setLeaveUsers(usersResult);else message.error(usersResult.message||'فهرست کارمندان دریافت نشد');await Promise.all([loadLeave(),loadPending()])}
  useEffect(()=>{load();loadFormReports()},[])
  const exportCsv=(rows:any[],name:string)=>{if(!rows?.length)return message.warning('داده‌ای برای خروجی وجود ندارد');const keys=Object.keys(rows[0]);const clean=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv='\uFEFF'+[keys.join(','),...rows.map(r=>keys.map(k=>clean(r[k])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`${name}.csv`;a.click();URL.revokeObjectURL(a.href)}
  const printPdf=(title:string,columns:{title:string;dataIndex:string;renderText?:(value:any,row:any)=>string}[],rows:any[])=>{if(!rows.length){message.warning('داده‌ای برای خروجی PDF وجود ندارد');return}const esc=(value:any)=>String(value??'—').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]||char));const popup=window.open('','_blank','width=1100,height=800');if(!popup){message.error('اجازه بازشدن پنجره چاپ را در مرورگر فعال کنید');return}const headers=columns.map(column=>`<th>${esc(column.title)}</th>`).join('');const body=rows.map(row=>`<tr>${columns.map(column=>`<td>${esc(column.renderText?column.renderText(row[column.dataIndex],row):row[column.dataIndex])}</td>`).join('')}</tr>`).join('');popup.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4 landscape;margin:12mm}body{font-family:Tahoma,Arial,sans-serif;direction:rtl;color:#222}h2{text-align:center;margin:0 0 8px}.meta{text-align:center;color:#666;margin-bottom:16px}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #777;padding:6px;text-align:center}th{background:#711452;color:#fff}tr:nth-child(even){background:#f8f1f6}@media print{button{display:none}}</style></head><body><h2>${esc(title)}</h2><div class="meta">تاریخ تهیه: ${new Date().toLocaleString('fa-IR')}</div><table><thead><tr>${headers}</tr></thead><tbody>${body}</tbody></table><script>window.onload=()=>{window.print()}<\/script></body></html>`);popup.document.close()}
  if(loading)return <div style={{height:420,display:'grid',placeItems:'center'}}><Spin size="large" tip="در حال خواندن گزارش از دیتابیس"/></div>
  if(!data)return <Alert type="error" showIcon message="گزارش‌ها از سرور دریافت نشد" action={<Button onClick={()=>load(true)}>تلاش مجدد</Button>}/>
  const cards=[
    {label:'کل نامه‌ها',value:data.summary.letterCount,color:'#8b1a6b',icon:<MailOutlined/>},
    {label:'وظایف فعال',value:data.summary.activeTasks,color:'#1677ff',icon:<CheckSquareOutlined/>},
    {label:'تیکت‌های باز',value:data.summary.openTickets,color:'#fa8c16',icon:<CustomerServiceOutlined/>},
    {label:'پیامک ارسال‌شده',value:data.summary.sentSms,color:'#722ed1',icon:<MessageOutlined/>},
    {label:'فرم در انتظار',value:data.summary.pendingForms,color:'#f5222d',icon:<FileTextOutlined/>},
    {label:'کاربران فعال',value:data.summary.activeUsers,color:'#52c41a',icon:<TeamOutlined/>}
  ]
  const letterColumns=[{title:'شماره',dataIndex:'number'},{title:'نوع',dataIndex:'type',render:(v:string)=><Tag>{typeLabel[v]||v}</Tag>},{title:'موضوع',dataIndex:'subject'},{title:'فرستنده',dataIndex:'from'},{title:'تاریخ',dataIndex:'date',render:faDate},{title:'وضعیت',dataIndex:'status',render:(v:string)=><Tag color="purple">{labelStatus(v)}</Tag>}]
  const taskColumns=[{title:'کد',dataIndex:'id',render:(v:string)=>`TSK-${v.slice(0,8)}`},{title:'عنوان',dataIndex:'title'},{title:'مسئول',dataIndex:'assignee',render:(v?:string)=>v||'—'},{title:'وضعیت',dataIndex:'status',render:(v:string)=><Tag color="blue">{labelStatus(v)}</Tag>},{title:'اولویت',dataIndex:'priority'},{title:'پیشرفت',dataIndex:'progress',render:(v:number)=>`${v}%`},{title:'مهلت',dataIndex:'dueDate',render:faDate}]
  const ticketColumns=[{title:'کد',dataIndex:'code'},{title:'عنوان',dataIndex:'title'},{title:'مشتری',dataIndex:'customer'},{title:'دسته',dataIndex:'category'},{title:'مسئول',dataIndex:'assignee',render:(v?:string)=>v||'—'},{title:'وضعیت',dataIndex:'status',render:(v:string)=><Tag color="orange">{labelStatus(v)}</Tag>},{title:'تاریخ ثبت',dataIndex:'createdAt',render:faDate}]
  const formColumns=[{title:'عنوان',dataIndex:'title'},{title:'ثبت‌کننده',dataIndex:'submitterName'},{title:'مدیر مستقیم',dataIndex:'managerName'},{title:'منابع انسانی',dataIndex:'hrName'},{title:'وضعیت',dataIndex:'status',render:(v:string)=><Tag color="magenta">{labelStatus(v)}</Tag>},{title:'ساعت مرخصی',dataIndex:'requestedHours'},{title:'تاریخ',dataIndex:'createdAt',render:faDate}]
  const leaveColumns=[{title:'نام و نام خانوادگی',dataIndex:'employeeName'},{title:'نوع مرخصی',dataIndex:'leaveKind'},{title:'تاریخ',dataIndex:'date'},{title:'زمان خروج',dataIndex:'startTime'},{title:'زمان ورود',dataIndex:'endTime'},{title:'ساعت',dataIndex:'requestedHours'},{title:'مدیر مستقیم',dataIndex:'managerName'},{title:'نظر مدیر',dataIndex:'managerDecision'},{title:'مدیر منابع انسانی',dataIndex:'hrManagerName'},{title:'نظر منابع انسانی',dataIndex:'hrDecision'},{title:'وضعیت',dataIndex:'status',render:(v:string)=><Tag color="magenta">{labelStatus(v)}</Tag>,renderText:(v:string)=>labelStatus(v)}]
  const pendingColumns=[{title:'فرم',dataIndex:'title'},{title:'کارمند',dataIndex:'submitterName'},{title:'مرحله جاری',dataIndex:'currentStage'},{title:'تأییدکننده فعلی',dataIndex:'currentApprover'},{title:'ساعت',dataIndex:'requestedHours'},{title:'روزهای انتظار',dataIndex:'waitingDays'},{title:'تاریخ ثبت',dataIndex:'createdAt',render:faDate,renderText:(v:string)=>faDate(v)}]
  const pie=(items:any[])=>items?.length?<ResponsiveContainer width="100%" height={260}><PieChart><Pie data={items} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90} label={({name,value})=>{const key=String(name||'');return `${labelStatus(typeLabel[key]||key)}: ${value}`}}>{items.map((_:any,i:number)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer>:<Empty/>
  return <div>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><div><h2 style={{margin:0}}>📊 گزارشات واقعی سیستم</h2><small style={{color:'#888'}}>تمام اعداد و جداول مستقیماً از دیتابیس خوانده شده‌اند</small></div><Space><Button icon={<ReloadOutlined/>} onClick={()=>load(true)}>به‌روزرسانی</Button><Button icon={<PrinterOutlined/>} onClick={()=>window.print()}>چاپ</Button></Space></div>
    <Row gutter={[12,12]} style={{marginBottom:16}}>{cards.map((c:any)=><Col xs={12} md={8} xl={4} key={c.label}><Card size="small" style={{borderTop:`4px solid ${c.color}`,borderRadius:12}}><Statistic title={c.label} value={c.value} prefix={<span style={{color:c.color}}>{c.icon}</span>}/></Card></Col>)}</Row>
    <Tabs items={[
      {key:'summary',label:'نمای کلی',children:<Row gutter={[16,16]}><Col xs={24} xl={16}><Card title="روند ثبت اطلاعات در ۶ ماه اخیر"><ResponsiveContainer width="100%" height={300}><BarChart data={data.monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="internalLetters" name="نامه داخلی" fill="#8b1a6b"/><Bar dataKey="incomingLetters" name="نامه وارده" fill="#1677ff"/><Bar dataKey="outgoingLetters" name="نامه صادره" fill="#52c41a"/><Bar dataKey="tasks" name="وظیفه" fill="#fa8c16"/><Bar dataKey="tickets" name="تیکت" fill="#722ed1"/><Bar dataKey="forms" name="فرم" fill="#f5222d"/></BarChart></ResponsiveContainer></Card></Col><Col xs={24} xl={8}><Card title="نوع نامه‌ها">{pie(data.letterTypes)}</Card></Col></Row>},
      {key:'letters',label:'نامه‌ها',children:<Card title="آخرین نامه‌های ثبت‌شده" extra={<Button icon={<DownloadOutlined/>} onClick={()=>exportCsv(data.letters,'letters-report')}>خروجی CSV</Button>}><Table rowKey="id" columns={letterColumns} dataSource={data.letters} scroll={{x:850}}/></Card>},
      {key:'tasks',label:'وظایف',children:<Row gutter={[16,16]}><Col xs={24} lg={8}><Card title="وضعیت وظایف">{pie(data.taskStatuses)}</Card></Col><Col xs={24} lg={16}><Card title="آخرین وظایف" extra={<Button icon={<DownloadOutlined/>} onClick={()=>exportCsv(data.tasks,'tasks-report')}>خروجی</Button>}><Table rowKey="id" columns={taskColumns} dataSource={data.tasks} scroll={{x:800}}/></Card></Col></Row>},
      {key:'tickets',label:'تیکت‌ها',children:<Row gutter={[16,16]}><Col xs={24} lg={8}><Card title="وضعیت تیکت‌ها">{pie(data.ticketStatuses)}</Card></Col><Col xs={24} lg={16}><Card title="آخرین تیکت‌ها" extra={<Button icon={<DownloadOutlined/>} onClick={()=>exportCsv(data.tickets,'tickets-report')}>خروجی</Button>}><Table rowKey="id" columns={ticketColumns} dataSource={data.tickets} scroll={{x:850}}/></Card></Col></Row>},
      {key:'forms',label:'فرم‌های سازمانی',children:<Tabs type="card" items={[
        {key:'leave-report',label:'گزارش مرخصی کارکنان',children:<Card title="گزارش مرخصی با فیلتر کارمند و تاریخ" extra={<Space><Button icon={<DownloadOutlined/>} onClick={()=>exportCsv(leaveRows,'leave-report')}>CSV</Button><Button type="primary" icon={<PrinterOutlined/>} onClick={()=>printPdf('گزارش مرخصی کارکنان',leaveColumns as any,leaveRows)} style={{background:'#8b1a6b'}}>خروجی PDF</Button></Space>}><Form form={leaveForm} layout="vertical" onFinish={loadLeave}><Row gutter={12}><Col xs={24} md={8}><Form.Item name="userId" label="کارمند"><Select allowClear showSearch optionFilterProp="label" placeholder="همه کارمندان" options={leaveUsers.map(user=>({value:user.id,label:`${user.fullName}${user.position?' — '+user.position:''}`}))}/></Form.Item></Col><Col xs={12} md={5}><Form.Item name="fromDate" label="از تاریخ"><PersianDatePicker/></Form.Item></Col><Col xs={12} md={5}><Form.Item name="toDate" label="تا تاریخ"><PersianDatePicker/></Form.Item></Col><Col xs={24} md={6} style={{display:'flex',alignItems:'center',paddingTop:14}}><Space><Button type="primary" htmlType="submit" loading={leaveLoading} style={{background:'#8b1a6b'}}>اعمال فیلتر</Button><Button onClick={()=>{leaveForm.resetFields();loadLeave()}}>پاک‌کردن</Button></Space></Col></Row></Form><Table rowKey="id" loading={leaveLoading} columns={leaveColumns} dataSource={leaveRows} scroll={{x:1300}} pagination={{pageSize:20}}/></Card>},
        {key:'pending',label:<span>فرایندهای تأییدنشده <Badge count={pendingRows.length}/></span>,children:<Card title="فرایندهای در انتظار تأیید" extra={<Space><Button icon={<ReloadOutlined/>} onClick={loadPending}>به‌روزرسانی</Button><Button type="primary" icon={<PrinterOutlined/>} onClick={()=>printPdf('فرایندهای تأییدنشده فرم‌های سازمانی',pendingColumns as any,pendingRows)} style={{background:'#8b1a6b'}}>خروجی PDF</Button></Space>}><Alert type="warning" showIcon message="این فهرست شامل فرم‌های منتظر مدیر مستقیم و منتظر منابع انسانی است" style={{marginBottom:12}}/><Table rowKey="id" columns={pendingColumns} dataSource={pendingRows} scroll={{x:900}} pagination={{pageSize:20}}/></Card>},
        {key:'overview',label:'نمای کلی فرم‌ها',children:<Row gutter={[16,16]}><Col xs={24} lg={8}><Card title="وضعیت فرم‌ها">{pie(data.formStatuses)}</Card></Col><Col xs={24} lg={16}><Card title="آخرین فرم‌ها" extra={<Button icon={<DownloadOutlined/>} onClick={()=>exportCsv(data.forms,'forms-report')}>خروجی</Button>}><Table rowKey="id" columns={formColumns} dataSource={data.forms} scroll={{x:900}}/></Card></Col></Row>}
      ]}/>}
    ]}/>
  </div>
}
